### ISSUE TITLE
Landing Page updates for Studio

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-home#383]
Hi @carlosgauci, 
We need some updates in the website landing page
### 1 - Add a new section about Studio
This section will have an H2 title, video, 3 bullet points and two buttons (button colors/text/link should be dynamic) and come right after the "Features" section. Both buttons should have the hover animation like most buttons on the website 

![Build even faster with Studio (free)](https://github.com/user-attachments/assets/14609638-ec9b-4a03-bf18-cc5c22266a8f)

We may change the CTA section into this format, so make sure that we can duplicate the content
```
  CTA:
    - title: Build even faster with Studio (free)
      link: (video or image link) 
      bullet points:
         - text 1
         - text 2
         - text 3
      buttons:
          - buttonText: Learn more
             buttonColor: dark blue
             url: https://landing.deepset.ai/deepset-studio
          - buttonText: Start building 
             buttonColor: green
             url: https://landing.deepset.ai/deepset-studio
```
### 2 - Add an extra button to Hero
I have made some changes in the code (#382 branch `studio-lauch-prep` ) to dynamically set the button color/text/link but these colored buttons should be next to each other when the screen is large enough 👇

![Build even faster with Studio (free) (1)](https://github.com/user-attachments/assets/e44cce1d-febe-428a-969c-915585298b91)

On smaller screens: 

<img width="987" alt="image" src="https://github.com/user-attachments/assets/36b5c616-84e7-4e47-8264-84a758e1d763">
